### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by durf1** [afklm/atlasman#29]
For each project we have links to JIRA, Confluence, Bitbucket, depending on plugins and  if project exists in the tool.

When i click on Confluence, the confluence space opens in a new tab.
When i click on JIRA or Bitbucket, the project is opened in the same tab atlasman was opened.

I would prefer all links open a new tab so atlasman remains open.

**Comment by mvdkleijn** [comment]
The link for Bamboo appears to be a link to the REST interface, not to the frontend... please fix that. The rest seems OK.

**Comment by mvdkleijn** [comment]
Tested and found fixed.
