### ISSUE TITLE
my repos/ all repos

### ISSUE THREAD

**Issue by Nehon** [afklm/atlasman#36]
Allow to switch from my repositories to all repositories

**Comment by mvdkleijn** [comment]
Has an issue. To reproduce:

- Projects
- Enable my projects only
- Search for a project
- Switch to all projects
- Remove / undo search
- Switch to my projects only

Result: no difference between "my projects" and "all projects". Some projects went missing in list. Force refresh of browser resets lists to working order.

**Comment by mvdkleijn** [comment]
Tested and verified as working
