### ISSUE TITLE
block http on CF

### ISSUE THREAD

**Issue by bv1p** [afklm/atlasman#38]
Your service (Atlasman) will always receive requests for both HTTP and HTTPS. Moreover, all of these requests will arrive on the same port. However, Cloudfoundry sets an extra HTTP header named x-forwarded-proto, whose value will be either http or https. This enables your service to distinguish between the two, and block the insecure HTTP connections.

https://docs.cloudfoundry.org/concepts/http-routing.html#round-robin

**Comment by mvdkleijn** [comment]
DoD:

- Atlasman should detect if HTTP is used
- Should auto-redirect to HTTPS
- If not available under HTTPS, Atlasman should refuse to function, instead displaying a single page error screen reminding the user to only use HTTPS.
